### ISSUE TITLE
Can't load module

### ISSUE THREAD

**Issue by lutzmor** [alexmohr/usb-can#19]
Hi i have a small problem, i build the driver on my raspberry pi and got it building but if i then do
`sudo insmod dev/usb-can/src/module/hlcan.ko
insmod: ERROR: could not insert module dev/usb-can/src/module/hlcan.ko: Invalid module format`

unsure what i did wrong :).

Greetings
Moritz

**Comment by alexmohr** [comment]
Please post the last couple of lines of the output from `dmesg` directly after inserting the module.

**Comment by lutzmor** [comment]
Sure sry :)

`[ 4373.205111] usb 1-1.1: SerialNumber: 1680FF0AC0846AAF7DCA555EC02000F5
[ 4373.211990] cdc_acm 1-1.1:1.0: ttyACM2: USB ACM device
[ 4373.515250] usb 1-1.2: new full-speed USB device number 45 using xhci_hcd
[ 4373.654804] usb 1-1.2: New USB device found, idVendor=1d50, idProduct=614e, bcdDevice= 1.00
[ 4373.654814] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4373.654821] usb 1-1.2: Product: lpc1769
[ 4373.654829] usb 1-1.2: Manufacturer: Klipper
[ 4373.654835] usb 1-1.2: SerialNumber: 0D40FF01C0846AAFA0A3555EC72000F5
[ 4373.657498] cdc_acm 1-1.2:1.0: ttyACM3: USB ACM device
[ 5067.961654] hlcan: disagrees about version of symbol module_layout`

i think the relevant part is the module_layout. But wait a moment testing something and reporting back :)

Greetings
Moritz

**Comment by lutzmor** [comment]
Got it working something went wrong with the kernel sources so the module was compiled against the wrong kernel, got this fixed and the kernel module loaded as expected :).

Thanks for the quick response will close this :)
