### ISSUE TITLE
Device attach failure

### ISSUE THREAD

**Issue by tahir1069** [alexmohr/usb-can#20]
I am trying to access a CAN bus data using an [adapter](https://www.amazon.de/Analysator-Intelligenter-Konverter-Adapter-Unterst%C3%BCtzung/dp/B07FY6T2WK/ref=sr_1_2_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=usb+can&qid=1621497458&sr=8-2-spons&psc=1&smid=A2F7JN9V2AWTSH&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzUU5PNVZJV1pQSkRPJmVuY3J5cHRlZElkPUEwNDA0OTk0M1FRWkVHS1QwQjdKMCZlbmNyeXB0ZWRBZElkPUEwMTExMjg0MUYzSko0RUhUT1FOWiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=) which looks [a little different](https://my.hidrive.com/lnk/0xiVyaLE) from the one in pictures in above link. 

One difference which I found [here](https://github.com/alexmohr/usb-can#usb-can-analyzer-linux-support) is in the device info.

The one on in example is:

```
Bus 002 Device 006: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
```
The one in my case is:
```
Bus 003 Device 022: ID 0471:1200 Philips (or NXP) 
```
Moreover my device is not attached as `/dev/tty**` due to which I am not able to use the adapter as described [here](https://github.com/alexmohr/usb-can#usage).

Any leads or suggestions will highly be appreciated.

**Comment by alexmohr** [comment]
Please post the make and model of your adapter. 
If your device does not show up as `tty` it's most probable not a serial to usb converter what the device this repo is made for actually is.

I'm pretty certain that your device is using a different protocol to communicate with the host system and is simply not supported by this implementation. 
With the NXP devices you have a good chance that there is a kernel driver made by NXP for your device.

**Comment by alexmohr** [comment]
Closing this because it seems invalid and received no response.

**Comment by Nable80** [comment]
I have a device with the same identifier (``0471:1200``) too and I think it has nothing to do with NXP/Philips. My one is based on PIC32MX795F512L with some (yet) unknown firmware and it definitely has a different protocol. I'm currently investigating how to work with it (there are some success reports on CSDN) and I hope it would be OK to post updates here in order to help those who come here from search engines.

**Comment by alexmohr** [comment]
Of course, feel free to post any results you find here. Once you got a working solution we can link this in the readme as well.
