### ISSUE TITLE
[3] write() failed: Input/output error

### ISSUE THREAD

**Issue by tandronescu** [alexmohr/usb-can#21]
Went through the readme and was able to follow along. The only modification I had to make was to explicitly declare skb_put_data() in hlcan.c above slc_bump because my kernel has a compiler flag on to treat implicit-function-declaration warnings as errors.

When I try to run the example commands I get the following: 
`sudo hlcand -F -s 500000 /dev/ttyUSB0
[6] starting on TTY device /dev/ttyUSB0
[3] write() failed: Input/output error`

Tried shorting RX/TX and and using loopback mode but I get the same result:
`sudo hlcand -F -s 500000 /dev/ttyUSB0 -m 1
[6] starting on TTY device /dev/ttyUSB0
[3] write() failed: Input/output error`

I am using a Jetson Xavier AGX on Ubunut 18.04.

All other terminal output suggests everything is in order. Any suggestions on how to fix this?

**Comment by alexmohr** [comment]
For the first part I'd be happy to accept a PR. 

To get some idea why the application fails:
* Please post the output of `lsusb`
* Check if your device is actually located at `/dev/ttyUSB0`
* Post the output of `dmesg` (maybe with `| grep hlcan` if the output is too large)

Shorting the pins is actually not necessary for loopback mode, it's all realized in software on the can adapter.
The board you are using already provides a can interface which might be a better choice

**Comment by tandronescu** [comment]
Made a PR

lsusb output: 
```
Bus 002 Device 005: ID 05e3:0749 Genesys Logic, Inc. 
Bus 002 Device 004: ID 2109:0817 VIA Labs, Inc. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 008: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 005: ID 291a:8346  
Bus 001 Device 007: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
Bus 001 Device 004: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Bus 001 Device 003: ID 2109:2817 VIA Labs, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

I think Device 007 is the one in question and shows up normally.

I did verify the device is at ttyUSB0: ls /dev | grep ttyUSB* gives
`ttyUSB0` with it plugged in and no output when it is unplugged.

The main thing dmesg shows is:
`[72855.067859] tty_warn_deprecated_flags: 'hlcand' is using deprecated serial flags (with no effect): 00008200`

**Comment by tandronescu** [comment]
It seems after some restarts and unplugging it is working now. Thanks for the help.

Ya, there is CAN via the GPIOs but I need more than 2 canbus so I was hoping to use a usb hub and some of these adapters.

**Comment by alexmohr** [comment]
Thanks, feel free to open a new issue if you encounter any more issues.
