### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by joe98477** [alexmohr/usb-can#23]
Seem to be getting this error when running the build script.

`pi@raspberrypi:~/usb-can $ ./build.sh
Building module
make -C /lib/modules/5.10.17-v7l+/build/ M=/home/pi/usb-can/src/module modules
make[1]: *** /lib/modules/5.10.17-v7l+/build/: No such file or directory.  Stop.
make: *** [Makefile:11: all] Error 2
Building userpace tools
cc -O2 -Wall -Wno-parentheses -D_GNU_SOURCE   hlcand.c   -o hlcand
`

**Comment by alexmohr** [comment]
Have you installed the linux kernel headers?

**Comment by joe98477** [comment]
I am using the raspberry pi. 
Please correct me if Im wrong - below is the install process I used.

`apt-get install can-utils`

`apt-get install raspberrypi-kernel-headers`

`git clone https://github.com/alexmohr/usb-can.git`

now if I try to insert module `insmod hlcan.ko` i get the following:

> pi@raspberrypi:~/usb-can $ insmod hlcan.ko
insmod: ERROR: could not load module hlcan.ko: No such file or directory

And a similar error when I try to use the build script.

> pi@raspberrypi:~/usb-can $ sudo ./build.sh install
Building module
mkdir -p /usr/lib/modules/5.10.17-v7l+/kernel/drivers/net/can
cp hlcan.ko /usr/lib/modules/5.10.17-v7l+/kernel/drivers/net/can
cp: cannot stat 'hlcan.ko': No such file or directory
make: *** [Makefile:16: install] Error 1
Building userpace tools
mkdir -p /usr/local/bin
cp -f hlcand  /usr/local/bin
cp: cannot stat 'hlcand': No such file or directory
make: *** [Makefile:66: install] Error 1

**Comment by alexmohr** [comment]
Building kernel modules on a raspbian is a bit tedious due to the kernel configuration.
Take a look at https://raspberrypi.stackexchange.com/a/40419

**Comment by alexmohr** [comment]
@joe98477 Do you need further help or can this be closed?

**Comment by joe98477** [comment]
Thanks for the reminder.
I gave up with the raspberry and used it on Ubuntu. Worked fine.

I did find that running build in each directory worked more reliably than the install script though.
