### ISSUE TITLE
Error in insmod command

### ISSUE THREAD

**Issue by alessio31183** [alexmohr/usb-can#28]
On Ubuntu 20.04 64 bit, after the insmod hlcan.ko command I get this reply

insmod: ERROR: could not load module hlcan.ko: No such file or directory

hlcan.ko is present in /usr/lib/modules/5.11.0-41-generic/kernel/drivers/net/can

I don't know how to solve

thanks

**Comment by alexmohr** [comment]
Sounds like you forgot to run the install step. This kernel module does not support dkms so you have to re-run the install step after each kernel update

**Comment by alexmohr** [comment]
Or provide the full path to the module when running insmod

**Comment by alessio31183** [comment]
Hi Alex,

with the full path I get this error

insmod: ERROR: could not insert module /usr/lib/modules/5.11.0-41-generic/kernel/drivers/net/can/hlcan.ko: Operation not permitted

Command is performed with sudo command of course

**Comment by alexmohr** [comment]
Have to run `./build.sh install` after the last kernel update?

I'm running ubuntu 20.04 as well so there is certainly no general issue with the module :)
Try the following:
* Run `dmesg -w`
* in a new terminal run all steps from the readme again (even if you ran them already). 
* Post the result of the `dmesg -w` here

**Comment by alessio31183** [comment]
I'm on Ubuntu 20.04 too

Did all your suggestions. This is the result of dmesg -w after the sudo insmod command

[150981.365813] usb 1-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[150981.365819] usb 1-2: Product: USB2.0-Serial
[150981.429960] usbcore: registered new interface driver usbserial_generic
[150981.429974] usbserial: USB Serial support registered for generic
[150981.434772] usbcore: registered new interface driver ch341
[150981.434793] usbserial: USB Serial support registered for ch341-uart
[150981.434822] ch341 1-2:1.0: ch341-uart converter detected
[150981.435683] usb 1-2: ch341-uart converter now attached to ttyUSB0
[151026.342982] Lockdown: insmod: unsigned module loading is restricted; see man kernel_lockdown.7

Thanks

**Comment by alexmohr** [comment]
The error message is right there ` [151026.342982] Lockdown: insmod: unsigned module loading is restricted; see man kernel_lockdown.7`

You have to sign the module, it's documented in the readme

**Comment by alessio31183** [comment]
I get this after trying the module signing

sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der src/module/hlcan.ko
[sudo] password di alessio: 
At main.c:248:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
kmodsign: /var/lib/shim-signed/mok/MOK.priv: No such file or directory

is something relative to Secure Boot enabled?

**Comment by alexmohr** [comment]
> is something relative to Secure Boot enabled?

Yes: wiki.ubuntu.com/UEFI/SecureBoot

Probably you have to run `sudo update-secureboot-policy --new-key`
I'm closing this as this is related to the setup of your machine and not an issue with the module
