### ISSUE TITLE
slcan Question

### ISSUE THREAD

**Issue by ThatcherC** [alexmohr/usb-can#41]
Hi! I'm very excited to have found this project - I recently got one of these CAN adapters and would love to use it with the `can-utils` ecosystem. I have one question on the README though: what does this section mean?

> **Please note that this module cannot be used together with slcan, make sure the module is not loaded and won't be loaded automatically!**

Should I remove/unload `slcan` before building and using `hlcan`? Or should I remove `hlcan` before I try to use `slcan` again? I think that part that's confusing me is

> make sure the module is not loaded

\- which module is being referred to there, `hlcan` or `slcan`?

Any advice is appreciated! Looking forward to running this!

**Comment by alexmohr** [comment]
Hi, 

> Should I remove/unload `slcan` before building and using `hlcan`? Or should I remove `hlcan` before I try to use `slcan` again? 

Actually both. The modules are mutually exclusive as `hlcan` is "pretending" to be `slcan` and it hijacks some things which are normally implemented by `slcan`

> - which module is being referred to there, `hlcan` or `slcan`?

As mentioned above you have to make sure that `hlcan` *or* `slcan` is loaded, never both.
