### ISSUE TITLE
Rewrite to kernel module

### ISSUE THREAD

**Issue by alexmohr** [alexmohr/usb-can#6]
Rewrite this project to a proper kernel module. 
After the rewrite this project will share most of its code with the slcan utils. 
The kernel module will be adjusted for the serial protocol and the slcand util will be ported to support this device.

Todo:
* Port the logic of the kernel module of slcan [DONE]
  * Receive  ✔️
  * Transmit    ✔️
  * Init   ✔️
* Port the slcand to use the new kernel module [DONE]
  * Init serial port ✔️
* Fix the travis build ✔️
* Document the new usage ✔️
  * Document that the implementation only supports the variable length protocol and not the fixed and how to setup the protocol
  * Add install script ✔️
  * Try to find the document which describes the configuration (again)
* Test [ TESTERS WANTED ]
  * Standard frame
  * Extended id 
  * variable dlc
  * load test 
  * valgrind ( for kernel module at least!)

**Comment by Ciusss89** [comment]
I'm working with the Standard frame and I can test it.

**Comment by alexmohr** [comment]
* Fixed hangup in kernel module
* Cannot be used together with slcan at the moment. Probably the slcan module must be blacklisted
* Testing must be done to see if general logic works again (Hardware is available in 10 Days from now)
* Replace handling of serial port to enable this module to be used along with slcan

**Comment by Ciusss89** [comment]
> I'm working with the Standard frame and I can test it.

Hi Alex,

I'm testing the standard frame, seems to be a little a bug (receive side), could you confirm:
 
The snippet is the output of candump:
```
  1  can0  000   [8]  02 03 04 05 06 07 08 55
  2  can0  000   [3]  02 03 55
  3  can0  000   [1]  55
  4  can0  000   [2]  22 33 55
```

1. I sent this: `01 02 03 04 05 06 07 08`
2. I sent this: `01 02 03`
2. I sent this: `77`
2. I sent this: `11 22 33`

I'm testing 9a683882d704

**Comment by alexmohr** [comment]
Which device mode do you use and what where the dlc of the messages?

**Comment by alexmohr** [comment]
slcan based version is more or less ready and working. Started developing native driver without the need of userspace tools

**Comment by Ciusss89** [comment]
> Which device mode do you use and what where the dlc of the messages?

I'm running it in mode 0.

Try to run this: https://pastebin.com/04euSQ8M

1. `sudo ./env_simulator.sh` 
It creates a vcan0 and run `candump`, `cangen`. 
2.  close the previous run and do this `sudo ./env_simulator.sh slcan0`. it runs candump and cangen on  `slcan0` (slcan0 is the iface made by your app)

if you compare the two outputs you can see that first and last byte are wrong you're using 2.

**Comment by alexmohr** [comment]
Your script is working for me. VCAN and HLCAN produce the same output. Could you post the output of the script from your machine?

**Comment by Ciusss89** [comment]
> Your script is working for me. VCAN and HLCAN produce the same output. Could you post the output of the script from your machine?

![Screenshot from 2020-04-13 15-51-32](https://user-images.githubusercontent.com/3006026/79126522-63c02e80-7da0-11ea-801c-dca4393b629a.png)

1. It's like the problem is visible only if we use real case. As u told me it is not reproducible by my script
